# Generated by Django 5.1.1 on 2026-04-27 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('pdf_file', models.FileField(upload_to='documents/pdfs/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(default='UPLOADED', max_length=30)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_file', models.ImageField(upload_to='documents/images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('document_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supporting_images', to='analyzer.documentset')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
