# Generated by Django 5.1.1 on 2026-04-27 13:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentset',
            name='upload_date',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='supportingimage',
            name='document_set',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image_files', to='analyzer.documentset'),
        ),
    ]
