# Generated by Django 5.1.1 on 2026-04-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analyzer', '0002_documentset_upload_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentset',
            name='image_extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentset',
            name='image_structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentset',
            name='pdf_extracted_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='documentset',
            name='pdf_structured_data',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='documentset',
            name='validation_result',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
